namespace TorznabClient.Models.Models;

public record TorznabRelease(
    string Title, 
    string Guid, 
    string Type, 
    string Description, 
    string Link, 
    string? Category = null,
    string? RageId = null, 
    string? TvDbId = null, 
    string? Imdb = null, 
    string? TmDbId = null,
    string? TvMazeId = null,
    string? TraktId = null,
    string? DoubanId = null,
    string? Genres = null,
    string? Languages = null,
    string? Subs = null,
    int? Year = null,
    string? Author = null,
    string? BookTitle = null,
    string? Publisher = null,
    string? Artist = null,
    string? Album = null,
    string? Label = null,
    string? Track = null,
    int? Seeders = null,
    int? Peers = null,
    string? Poster = null,
    string? InfoHash = null,
    string? MagnetUri = null,
    double? MinimumRatio = null,
    int? MinimumSeedTime = null,
    double? DownloadVolumeFactor = null,
    double? UploadVolumeFactor = null
);